[server]
headless = true
port = 8501
enableCORS = false
enableWebsocketCompression = false

[theme]
backgroundColor = "#0E1017"  # Customize the background color
secondaryBackgroundColor = "#272630"  # Customize the sidebar background color
textColor = "#ffffff"  # Customize the text color
